<?php
/**
 * @file
 * Module file for training module.
 */

define('TRAINING_BLOCK_RATES_SERVICE', 'http://www.nbrb.by/Services/XmlExRates.aspx');

/**
 * Implements hook_menu().
 */
function training_menu() {
  $menu = array();
  $menu['training/menu'] = array(
    'title' => 'Training Landing Page',
    'description' => 'This page is Landing Page',
    'page callback' => 'training_page_html',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'expanded' => TRUE,
  );
  $menu['training/menu/custom_access'] = array(
    'title' => 'Custom Access Menu Item',
    'description' => 'This page is accessible to authenticated users only',
    'page callback' => 'training_page_html',
    'access callback' => 'training_custom_access',
    'access arguments' => array('authenticated user'),
    'file' => 'training.pages.inc',
  );
  $menu['training/menu/permissioned'] = array(
    'title' => 'Permissioned Menu Item',
    'description' => 'This page is accessible to permissioned users only',
    'page callback' => 'training_page_html',
    'access arguments' => array('train'),
    'file' => 'training.pages.inc',
  );
  $menu['training/menu/callback'] = array(
    'title' => 'Callback Menu Item',
    'page callback' => 'training_menu_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/menu/tabs'] = array(
    'title' => 'Tabs Pages',
    'page callback' => 'training_menu_tabs_default',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/menu/tabs/first'] = array(
    'title' => 'Tabs',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'weight' => -1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $menu['training/menu/tabs/second'] = array(
    'title' => 'Second',
    'page callback' => 'training_menu_tabs',
    'page arguments' => array(3),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
  );
  $menu['training/menu/tabs/third'] = array(
    'title' => 'Third',
    'page callback' => 'training_menu_tabs',
    'page arguments' => array(3),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
  );
  $menu['training/menu/tabs/fourth'] = array(
    'title' => 'Fourth',
    'page callback' => 'training_menu_tabs',
    'page arguments' => array(3),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );
  $menu['training/menu/tabs/default/first'] = array(
    'title' => 'Default secondary tab',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'tab_parent' => 'training/menu/tabs/first',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $menu['training/menu/tabs/default/second'] = array(
    'title' => 'second',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'tab_parent' => 'training/menu/tabs/first',
    'type' => MENU_LOCAL_TASK,
  );
  $menu['training/menu/tabs/default/third'] = array(
    'title' => 'third',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'tab_parent' => 'training/menu/tabs/first',
    'type' => MENU_LOCAL_TASK,
  );
  $menu['training/menu/arguments/%/%'] = array(
    'title' => 'Menu arguments',
    'page callback' => 'training_menu_arguments',
    'page arguments' => array(3, 4),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/menu/placeholder/%/display'] = array(
    'title' => 'Menu argument before display',
    'page callback' => 'training_menu_arguments_display',
    'page arguments' => array(3),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/menu/default_arg/%digit'] = array(
    'title' => 'Menu preprocessing argument',
    'page callback' => 'training_menu_arguments_preprocessing',
    'page arguments' => array(3),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/menu/title'] = array(
    'title callback' => 'training_menu_title_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/menu/main'] = array(
    'title' => 'Item in main menu',
    'menu_name' => 'main-menu',
    'access arguments' => array('train'),
    'file' => 'training.pages.inc',
  );
  $menu['training/theme'] = array(
    'title' => 'Training Theme',
    'description' => 'This page is Training Theme page',
    'page callback' => 'training_theme_html',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'expanded' => TRUE,
  );
  $menu['training/theme/table'] = array(
    'title' => 'Table Theme',
    'description' => 'This page is Table Theme page',
    'page callback' => 'training_theme_table',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/theme/image'] = array(
    'title' => 'Image Theme',
    'description' => 'This page is Image Theme page',
    'page callback' => 'training_image_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/theme/access'] = array(
    'title' => 'Access Theme',
    'description' => 'This page is Access Theme page',
    'page callback' => 'training_access_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/form'] = array(
    'title' => 'Form Example',
    'description' => 'This page is Form Example',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('training_google_form'),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/entity'] = array(
    'title' => 'Entity Example',
    'description' => 'This page is Entity Example',
    'page callback' => 'training_example_entity_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/message'] = array(
    'title' => 'Text Message',
    'description' => 'This page is Text Message page',
    'page callback' => 'training_text_message_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/message/add'] = array(
    'title' => 'Add new Text Message',
    'description' => 'Add a new Text Message',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('text_message_form'),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  $menu['training/message/edit/%'] = array(
    'title' => 'Edit Text Message',
    'description' => 'Edit current Text Message',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('text_message_form', 3),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/js'] = array(
    'title' => 'Javascript',
    'description' => 'CTools example. JS',
    'page callback' => 'training_js_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/ctools/ajax'] = array(
    'title' => 'CTools AJAX',
    'description' => 'CTools example. Ajax',
    'page callback' => 'training_ajax_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/ctools/ajax/callback-text'] = array(
    'title' => 'CTools AJAX',
    'description' => 'CTools example. Ajax text',
    'page callback' => 'training_ajax_callback_text',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/ctools/cleanstring'] = array(
    'title' => 'CTools cleanstring',
    'description' => 'CTools example. Cleanstring',
    'page callback' => 'training_cleanstring_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/ctools/dependent'] = array(
    'title' => 'CTools dependent',
    'description' => 'CTools example. Dependent',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('training_dependent_form'),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/ctools/math'] = array(
    'title' => 'CTools math expressions',
    'description' => 'CTools example. Math',
    'page callback' => 'training_math_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/ctools/modal'] = array(
    'title' => 'CTools modal',
    'description' => 'CTools example. Modal',
    'page callback' => 'training_modal_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/ctools/modal/%ctools_js/form'] = array(
    'title' => 'CTools modal',
    'description' => 'CTools example. Modal form',
    'page callback' => 'training_modal_form_callback',
    'page arguments' => array(3),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/ctools/tabs'] = array(
    'title' => 'CTools tabs',
    'description' => 'CTools example. Tabs',
    'page callback' => 'training_tabs_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/ctools/object-cache'] = array(
    'title' => 'CTools object cache',
    'description' => 'CTools example. Object cache',
    'page callback' => 'training_object_cache_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/files'] = array(
    'title' => 'Files Download',
    'description' => 'This page is Files Download page',
    'page callback' => 'training_files_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/files/%ctools_js/load_form'] = array(
    'title' => 'Load file',
    'description' => 'Load files',
    'page callback' => 'training_load_form_callback',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/i18n'] = array(
    'title' => 'Internationalisation sandbox',
    'description' => 'Page demonstrates example for localisation in Drupal',
    'page callback' => 'training_i18n_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/dates'] = array(
    'title' => 'Dates sandbox',
    'description' => 'Page demonstrates example for dates in Drupal',
    'page callback' => 'training_dates_callback',
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
  );
  $menu['training/dates/%ctools_js/form'] = array(
    'title' => 'Show date',
    'description' => 'Shows date of users registration',
    'page callback' => 'training_dates_form_callback',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'file' => 'training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $menu['training/security'] = array(
    'title' => 'Security sandbox',
    'description' => 'Page demonstrates example for security in Drupal',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('training_security_form'),
    'access arguments' => array('access content'),
    'file' => 'training.pages.inc',
  );
  $menu['training/token'] = array(
    'title' => 'Token sandbox',
    'description' => 'Page demonstrates example for tokens in Drupal',
    'page callback' => 'training_token_callback',
    'access arguments' => array('access content'),
    'file' => 'training.pages.inc',
  );
  $menu['training/rules'] = array(
    'title' => 'Rules sandbox',
    'description' => 'Page demonstrates example for rules in Drupal',
    'page callback' => 'training_rules_callback',
    'access arguments' => array('access content'),
    'file' => 'training.pages.inc',
  );
  $menu['training/performance'] = array(
    'title' => 'Performance',
    'description' => 'Page demonstrates example for performance in Drupal',
    'page callback' => 'training_performance_callback',
    'access arguments' => array('access content'),
    'file' => 'training.pages.inc',
  );
  $menu['training/services'] = array(
    'title' => 'Services',
    'description' => 'Page demonstrates example for services in Drupal',
    'page callback' => 'training_services_callback',
    'access arguments' => array('access content'),
    'file' => 'training.pages.inc',
  );
  $menu['training/lottery'] = array(
    'title' => 'Lottery',
    'description' => 'Page of some lottery',
    'page callback' => 'training_lottery_callback',
    'access arguments' => array('access content'),
    'file' => 'training.pages.inc',
  );

  return $menu;
}

/**
 * Implements hook_flush_caches().
 */
function training_flush_caches() {
  return array(
    'cache_training_performance',
    'cache_training_lottery',
  );
}

/**
 * Implements hook_views_api().
 */
function training_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'training') . '/views',
  );
}

/**
 * Implements hook_mail().
 */
function training_mail($key, &$message, $params) {
  $pattern = 'The current training id is [current_training:id]';
  $pattern_processed = token_replace($pattern);
  $message['title'] = t('Test');
  $message['body'][] = $pattern_processed;
}

/**
 * Implements hook_file_download().
 */
function training_file_download($uri) {
  global $user;
  $table = 'file_managed';
  $alias = 'fm';
  $uid = _training_select_uid_from_db($table, $alias);
  if (in_array($user->uid, $uid)) {
    return array('Content-Type' => file_get_mimetype($uri));
  }
  else {
    return -1;
  }
}

/**
 * Implements hook_node_grants().
 */
function training_node_grants($account, $op) {
  $grants = array();
  if ($account->uid  && $op == 'view' && user_access('access content', $account)) {
    $grants['training_author_text_message'] = array($account->uid);
  }

  return $grants;
}

/**
 * Implements hook_node_access_records().
 */
function  training_node_access_records($node) {
  if ($node->type == 'article') {
    $table = 'text_message';
    $alias = 'tm';
    $uid = _training_select_uid_from_db($table, $alias);
    $grants = array();
    foreach ($uid as $value) {
      $grants[] = array(
        'realm' => 'training_author_text_message',
        'gid' => $value,
        'grant_view' => 1,
        'grant_update' => 0,
        'grant_delete' => 0,
        'priority' => 0,
      );
    }

    return $grants;
  }
}

/**
 * Implements hook_permission().
 */
function training_permission() {
  $permission = array(
    'train' => array(
      'title' => 'Access protected menu example',
      'description' => 'Use this to control access to page Permissioned Menu Item of training module',
    ),
    'train_theme' => array(
      'title' => 'Access protected content',
      'description' => 'Use this to control access to page Access Theme of training module',
    ),
  );

  return $permission;
}

/**
 * Implements hook_block_info().
 */
function training_block_info() {
  $blocks['exchange'] = array(
    'info' => t('Exchange'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['tr_no_cache'] = array(
    'info' => t('Training: No cache'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['tr_cache_per_role'] = array(
    'info' => t('Training: Per role'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['lottery'] = array(
    'info' => t('Lottery number'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function training_block_view($delta = '') {
  global $user;
  $obj_lottery = cache_get('cache_for_message_' . $user->uid, 'cache_training_lottery');
  if ($obj_lottery && isset($obj_lottery->data->lottery_num)) {
    $messages = implode('</br>', $obj_lottery->data->lottery_num);
  }
  else {
    $messages = t('Sorry, you have not won anything yet :(');
  }
  $date = variable_get('training_date_update_rates_service', array());
  $data = variable_get('training_data_rates_service', array());
  $rows = array();
  $block = array();
  foreach ($data as $value) {
    if (variable_get('check' . $value['CharCode'])) {
      $rows[] = array(
        $value['Name'],
        $value['CharCode'],
        $value['Rate'],
      );
    }
  }
  if ($delta == 'exchange' && !empty($date)) {
    $block['subject'] = t('Title block');
    $block['content'] = t('Обновлено %date', array('%date' => $date)) .
      theme('table', array('rows' => $rows));
  }
  if ($delta == 'tr_no_cache') {
    $block['subject'] = t('No cache');
    $block['content'] = array(
      '#theme' => 'training_render_stub',
      '#type' => 'tr_no_cache',
    );
  }
  if ($delta == 'tr_cache_per_role') {
    $block['subject'] = t('Cache per role');
    $block['content'] = t('test') . rand(1, 100);
  }
  if ($delta == 'lottery') {
    $block['subject'] = t('Oooh, You win in following lottery!');
    $block['content'] = $messages;
  }

  return $block;
}

/**
 * Implements hook_block_configure().
 */
function training_block_configure($delta = '') {
  $form = array();
  if ($delta == 'exchange') {
    $data = variable_get('training_data_rates_service', array());
    foreach ($data as $value) {
      $form['check' . $value['CharCode']] = array(
        '#type' => 'checkbox',
        '#title' => $value['Name'],
        '#default_value' => variable_get('check' . $value['CharCode'], array()),
      );
    }
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function training_block_save($delta = '', $edit = array()) {
  if ($delta == 'exchange') {
    $data = variable_get('training_data_rates_service', array());
    foreach ($data as $value) {
      variable_set('check' . $value['CharCode'], $edit['check' . $value['CharCode']]);
    }
  }
}

/**
 * Implements hook_cron().
 */
function training_cron() {
  $default = REQUEST_TIME;
  $last_crone = variable_get('last_start', $default);
  //sets the start-up period (15 min).
  if ($default-$last_crone >= 900) {
    variable_set('last_start', REQUEST_TIME);
    _training_rates_batch();
  }
}

/**
 * Implements hook_theme().
 */
function training_theme() {
  $theme = array();
  $theme['test_form_theme_function'] = array(
    'render element' => 'form',
    'arguments' => array('form' => NULL),
  );
  $theme['training_render_stub'] = array(
    'variables' => array('type' => NULL),
  );

  return $theme;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function training_form_user_login_block_alter(&$form, &$form_state, $form_id) {
  array_unshift($form['#validate'], 'secret_key_validate');
  $form['#theme'] = 'test_form_theme_function';
  $form['name']['#weight'] = -2;
  $form['pass']['#weight'] = -1;
  $form['secret_key'] = array(
    '#type' => 'textfield',
    '#title' => 'Secret Key',
    '#size' => 15,
    '#weight' => 0,
  );
  if (isset($form_state['input']['secret_key']) && $form_state['input']['secret_key'] == 'OpenSimSim') {
    $form['name']['#required'] = FALSE;
    $form['pass']['#required'] = FALSE;
  }
  $form['#submit'][] = 'secret_key_submit';
  $form['#attached']['css'] = array(
    drupal_get_path('module', 'training') . '/css/training.css',
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function training_field_formatter_info() {
  return array(
    'text_formated' => array(
      'lable' => t('Formated text'),
      'field types' => array('text'),
      'settings' => array(
        'format' => '%s',
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function training_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();
  if ($display['type'] == 'text_formatted') {
    $element['format'] = array(
      '#title' => t('Format'),
      '#type' => 'textfield',
      '#size' => 20,
      '#default_value' => $settings['format'],
      '#required' => TRUE,
    );
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function training_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = t('Use a "@format" format to display this field', array(
    '@format' => $settings['format'],
  ));

  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function training_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];
  switch ($display['type']) {
    case 'text_formated':
      foreach ($items as $delta => $item) {
        $element[$delta] = array('#markup' => sprintf($settings['format'], $item['value']));
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_entity_info().
 */
function training_entity_info() {
  return array(
    'training_item' => array(
      'label' => t('Task'),
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'base table' => 'training',
      'fieldable' => FALSE,
      'entity keys' => array(
        'id' => 'id',
      ),
      'load hook' => 'training_item_load',
      'label callback' => 'entity class label',
      'uri callback' => 'entity class uri',
      'module' => 'training',
      'access callback' => 'training_access',
    ),
    'text_msg' => array(
      'label' => t('Text message'),
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'base table' => 'text_message',
      'fieldable' => FALSE,
      'entity keys' => array(
        'id' => 'id',
      ),
      'load hook' => 'text_msg_load',
      'label callback' => 'entity class label',
      'uri callback' => 'entity class uri',
      'module' => 'training',
      'access callback' => 'training_access',
    ),
  );
}

/**
 * Implements hook_entity_property_info_alter().
 */
function training_entity_property_info_alter(&$info) {
  $info['training_item']['properties']['uid']['type'] = 'user';
  $info['training_item']['properties']['uid']['setter callback'] = 'entity_property_verbatim_set';
  $info['training_item']['properties']['uid']['setter permission'] = 'administer nodes';
  $info['text_msg']['properties']['title']['setter callback'] = 'entity_property_verbatim_set';
  $info['text_msg']['properties']['body']['setter callback'] = 'entity_property_verbatim_set';
}

/**
 * Implements hook_xmlrpc().
 */
function training_xmlrpc() {
  $methods[] = array(
    'training_services.test',
    '_training_services_test',
    array(
      'int', //return type
      'int',
      'string',
    ),
    t('Returns some test data.'),
  );
  $methods[] = array(
    'training_services.lottery',
    '_training_services_lottery',
    array(
      'string', //return type
      'int',
    ),
    t('Returns lottery code.'),
  );

  return $methods;
}

/**
 * Check access for page Custom Access Menu Item.
 *
 * @param string $role_name
 *   The role required for access.
 *
 * @return bool
 *   True if the acting user has the role specified.
 */
function training_custom_access($role_name) {
  global $user;

  return in_array($role_name, $user->roles);
}

/**
 * Displays a specific string, depending on a number in the address bar.
 *
 * @param int $arg
 *   Integer argument in the address bar.
 *
 * @return string
 *   A string that corresponds to an integer in the address bar, or NULL if there is no match.
 */
function digit_load($arg) {
  switch ($arg) {
    case 1:
      $arg = 'one';
      break;
    case 2:
      $arg = 'two';
      break;
    case 3:
      $arg = 'three';
      break;
    case 99:
      $arg = 'Almost there';
      break;
    default:
      $arg = NULL;
  }

  return $arg;
}

/**
 * Renames the title dynamically.
 *
 * @return string
 *   A string that contents dynamic title.
 */
function training_menu_title_callback() {
  global $user;
  $user_name = isset($user->name) ? $user->name : 'anonymous';

  return 'Dynamic title: username = ' . $user_name;
}

/**
 * Validates form user_login_block.
 *
 * Validates element secret_key and logs in current user as admin.
 */
function secret_key_validate($form, &$form_state) {
  if ($form_state['values']['secret_key'] == 'OpenSimSim') {
   $form_state['values']['name'] = 'admin';
   $form_state['values']['pass'] = 'admin';
  }
}

/**
 * Submits form user_login_block.
 */
function secret_key_submit($form, &$form_state) {
  if ($form_state['values']['secret_key'] == 'OpenSimSim') {
    user_load(1);
    user_login_finalize($form_state);
  }
}

/**
 * Themes a custom layout for user_login_block.
 *
 * @return string
 *  String contents HTML tags for custom layout.
 */
function theme_test_form_theme_function($form) {
  $attributes = array(
    'id' => 'table-test-login',
  );
  $rows = array(
    array(
      drupal_render($form['form']['name']),
    ),
    array(
      drupal_render($form['form']['pass']),
    ),
    array(
      drupal_render($form['form']['secret_key']),
    ),
    array(
      drupal_render($form['form']['actions']['submit']),
    ),
    array(
      drupal_render($form['form']['links']) .
      drupal_render($form['form']['form_build_id']) .
      drupal_render($form['form']['form_id']),
    ),
  );

  return theme('table', array(
    'rows' => $rows,
    'attributes' => $attributes,
  ));
}

/**
 * Themes a custom layout for tr_no_cache and tr_cache_per_role blocks.
 */
function theme_training_render_stub($variables) {
  $output = $variables['type'] . ':' . rand(1, 100);

  return $output;
}

/**
 * Creates array of users id from db.
 *
 * Select from table text_message users id who created text message.
 *
 * @param string $table
 *   Table name.
 * @param string $alias
 *   Table alias.
 *
 * @return array $table
 *   Returns array of users id.
 */
function _training_select_uid_from_db($table, $alias) {
  $uid = array();
  $query = db_select($table, $alias);
  $query
    ->fields($alias, array('uid'))
    ->distinct();
  $uid = $query->execute()->fetchCol();

  return $uid;
}

/**
 * Sends a request to the rates service.
 *
 * Parses the xml data. Converts xml object properties to string,
 * writes them to arrays. The resulting arrays sets in the variables.
 *
 * @param array $context
 */
function _training_request_rates_service(&$context) {
  $date = '';
  $array_data = array();
  $request = drupal_http_request(TRAINING_BLOCK_RATES_SERVICE);
  if (!empty($request) && isset($request->data)) {
    $data = new SimpleXMLElement($request->data);
    foreach ($data->Currency as $value) {
      $array_data[] = array(
        'CharCode' => (string) $value->CharCode,
        'Name' => (string) $value->Name,
        'Rate' => (string) $value->Rate,
      );
    }
    foreach ($data->attributes() as $key => $val) {
      $date .= (string) $val;
    }
    $context['results']['array_data'] = $array_data;
    $context['message'] = t('Import rate');
    variable_set('training_data_rates_service', $array_data);
    variable_set('training_date_update_rates_service', $date);
  }
}

/**
 * Deletes data of exchange to db.
 *
 * Selects data from table 'training_exchange'.
 * Deletes records before overwriting.
 *
 * @param array $context
 */
function _training_delete_rates_service_from_db(&$context) {
  $query = db_select('training_exchange', 'tex');
  $query
    ->fields('tex', array('id', 'name'));
  $result = $query->execute()->fetchAll();
  if (!empty($result)) {
    foreach ($result as $value) {
      db_delete('training_exchange')
        ->condition('id', $value->id)
        ->execute();
      $context['message'] = t('Delete !name', array('!name' => $value->name));
    }
  }
  else {
    $context['message'] = t('Preparing to write to db.');
  }
}

/**
 * Inserts data of exchange to db.
 *
 * @param array $context
 */
function _training_insert_db_rates_service(&$context) {
  foreach ($context['results']['array_data'] as $value) {
    $record = array(
      'char_code' => $value['CharCode'],
      'name' => $value['Name'],
      'rate' => $value['Rate'],
    );
    drupal_write_record('training_exchange', $record);
    $context['message'] = t('Insert !name.', array('!name' => $value['Name']));
  }
}

/**
 * Creates batch task.
 *
 * Imports exchange data. Inserts them to db.
 */
function _training_rates_batch() {
  $batch = array (
    'title' => t('Import rate'),
    'operations' => array(
      array('_training_request_rates_service', array()),
      array('_training_delete_rates_service_from_db', array()),
      array('_training_insert_db_rates_service', array()),
    ),
  );
  batch_set($batch);
  batch_process();
}

/**
 * Loads data based on user id.
 *
 * @param $uid
 *   User ID.
 *
 * @return array
 */
function _training_performance_load_data($uid) {
  $cache = &drupal_static(__FUNCTION__, NULL);
  if (!isset($cache[$uid])) {
    if (!isset($cache['select'])) {
      $cache['select'] = db_select('node', 'n')->fields('n');
    }
    $select = clone $cache['select'];
    $select->condition('uid', $uid);
    $cache[$uid] = $select->execute()->fetchAllAssoc('nid');
  }

  return $cache[$uid];
}

/**
 * Returns some test data.
 *
 * XML-RPC callback for training_services.test.
 *
 * @param int $arg1
 * @param string $arg2
 *
 * @return int
 */
function _training_services_test($arg1, $arg2) {
  if ($arg1 == '10000') {
    return xmlrpc_error(10000, t('Invalid argument'));
  }

  return $arg1 * $arg2;
}

/**
 * Checks some conditions for generate success code.
 *
 * @return string
 */
function _training_lottery_generator_success() {
    $server = url($GLOBALS['base_url'] . '/xmlrpc.php', array('external' => TRUE));
  $options = array(
    'training_services.lottery' => array(
      rand(1, 2),
    ),
  );
  $success = xmlrpc($server, $options);

  return $success;
}

/**
 * Returns success code for lottery.
 *
 * XML-RPC callback for training_services.lottery.
 *
 * @param int $arg1
 *   Random integer.
 * @param int $arg2
 *   Random integer.
 *
 * @return string
 */
function _training_services_lottery($arg1) {
  $arg2 = rand(1, 2);
  if ($arg1 == $arg2) {
    return 'success';
  }

  return 'no success';
}
